### ISSUE TITLE
Stderr to sdout redirection in shellpipe

### ISSUE THREAD

**Issue by olethanh** [reinh/vim-makegreen#1]
Some "make" program use stderr instead of stdout and so don't work with vim-makegreen which change the shellpipe to > while they work with :make
Ex: nosetests which is a unit testing framework for python

This small patch change the shell pipe to 2>&1 so that it works with nosetests
http://github.com/olethanh/vim-makegreen/tree/stderr

Regards
  Olivier

**Comment by reinh** [comment]
Merged. Thanks very much for the contribution.

**Comment by olethanh** [comment]
Hum I'm really really sorry but this patch is actually not working and I didn't notice because the previous quickdiff result was retained.
Could you remove the patch please?

**Comment by olethanh** [comment]
It's actually missing a > afterwards to redirect the output to the file, but that still wouldn't work since in bash only stdout is written if you put the >filename after the 2&>1 and vim won't allow it to be before.

So that leave us with 3 solutions :
- Use 2> instead of > but that ignore normal stdout output
- Allow user to specify their own shellpipe to be used in vim-makegreen
- Use 2>&1 | tee >/dev/null which is hackish and ugly
- Use &> which is the standard to redirect both output to a file bit but only work since Bash 4.0

What is your opinion?

**Comment by reinh** [comment]
Woops! No worries. I would probably prefer towards `&>`. Bash 4.0 has been around for a decent while and it also works for zsh.

**Comment by olethanh** [comment]
Ok, I have updated my branch to do that. Thanks

**Comment by reinh** [comment]
Merged. Thanks!

**Comment by reinh** [comment]
Ok, after more consideration (and given the non-portability of `&>`), I've decided not to set the shellpipe. makegreen is makeprg agnostic, so it isn't makegreen's responsibility to make any particular executable work properly, just like it isn't :make's. If you want to use `&>`, you are free to set the shellpipe yourself.
