### ISSUE TITLE
The test runner reports success if there are exceptions thrown in the spec

### ISSUE THREAD

**Issue by tom-pang** [reinh/vim-makegreen#3]
For example:

```
describe 'rspec make plugin' do
  it 'should error on the following in a bare file' do
    Foo.new
  end
end
```

The above in a bare file should result in the tests failing, but vim-makegreen reports them as all running. If I change the assertion to something knowably false (like false.should be_true), only then do the tests report an error.

**Comment by tom-pang** [comment]
If you replace the rspec compiler with the below file, then this is fixed. rspec.vim badly needs the error formatting from rails.vim ported to it, but this covers most of the bases for now.

http://gist.github.com/644066

**Comment by reinh** [comment]
This is, as noted, a failure of the rspec compiler's errorformat. There is a deeper issue in that if the specs totally fail to run, you will get a green bar. I need to see if I can check the exit code of makeprogram.

**Comment by reinh** [comment]
BTW the updated rspec compiler should be contributed back to the ruby.vim project if it hasn't already been. IIRC tpope has commit rights so it should be.

I'm closing this since it isn't a makegreen issue per se.

**Comment by tom-pang** [comment]
Sure. The updated rspec compiler (unfortunately) breaks everything else with error parsing (and hence hasn't been accepted). Need to rework it at some point.
