### ISSUE TITLE
Make arguments should be configurable

### ISSUE THREAD

**Issue by garybernhardt** [reinh/vim-makegreen#5]
Right now, the plugin always does "make %". This breaks in some situations (e.g., a Rails controller isn't even requireable on its own because ApplicationController won't be defined). My compiler runs all tests all the time anyway, so this breakage is doubly annoying for me.

In general, I don't like that the plugin always runs ":make %". I'd like to see the default be :make with no args, combined with a way to run on custom args if the user wants to map something for that.

Thoughts?

**Comment by garybernhardt** [comment]
Rick Harding just forked the project to customize it for his make arguments:

https://github.com/mitechie/vim-makegreen/commit/80af38726abb53c4d28263742837f44c77e2bbd5

It's not just me! :)

**Comment by garybernhardt** [comment]
Damn it... I just accidentally closed this and can't re-open it. That button position is crap, man.

**Comment by reinh** [comment]
So perhaps a sensible default and a configuration option? Is "%" still a sensible default?

**Comment by garybernhardt** [comment]
I think that "%" is sensible enough. For my own use in Ruby, I'll always want "spec" as the default arg, but I can use this customization point to do that.

My preferred solution would be to expose a function that the user can map, passing in whichever args he wants (or computing them based on the current file, as in Rich Harding's change).

Thoughts? I can hack a patch up if that sounds reasonable.

**Comment by garybernhardt** [comment]
A proposed change is in my master. I removed the noremap chain because it was confusing me and didn't seem to do anything, especially with MakeGreen() now being a public function.

Commit: garybernhardt/vim-makegreen@743c911c9111a46b8eff8d84a8fbe2b82d4c800b
Example use in my vimrc: garybernhardt/dotfiles@e74642ff398cc8a012e0902b7f3c1fc7c3aed7cf

**Comment by reinh** [comment]
Great, merged into master. Thanks!
