### ISSUE TITLE
Mapping conflicts with command-T

### ISSUE THREAD

**Issue by silopolis** [reinh/vim-makegreen#9]
Hi and thanks a lot for this plugin.
<leader>t conflicts with command-T default mapping (which would better be <leader>ct IMHO)... may I suggest <leader>mg as a replacement ?!

Bests

**Comment by reinh** [comment]
You may suggest it right in your .vimrc:

```
map <Leader>mg :call MakeGreen()<cr>
```

The plugin only creates the mapping if one doesn't already exist.

**Comment by silopolis** [comment]
Hi,

2011/6/3 reinh <
reply@reply.github.com>

> You may suggest it right in your .vimrc:
> 
>    map <Leader>mg :call MakeGreen()<cr>
> 
> The plugin only creates the mapping if one doesn't already exist.

Indeed that's what I did
This was just so that there is no conflict by default between two major
plugins

Thanks for your reply
Bests
